# This configuration was created from a template file.  Before making changes,
# please make sure that you do not have a process in place that would override
# your changes in the future.  The accompanying .env file might be the correct
# place for customizations instead.
version: '3.4'

x-osserver:
  &default-osserver
  image: __DEFAULT_DOCKER_REGISTRY__openslides-server:latest
  networks:
    - front
    - back
  restart: always
x-osserver-env: &default-osserver-env
    AMOUNT_REPLICAS: 1
    AUTOUPDATE_DELAY: 1
    DEMO_USERS: ""
    CONNECTION_POOL_LIMIT: 100
    DATABASE_HOST: "pgbouncer"
    DATABASE_PASSWORD: "openslides"
    DATABASE_PORT: 5432
    DATABASE_USER: "openslides"
    DEFAULT_FROM_EMAIL: "noreply@example.com"
    DJANGO_LOG_LEVEL: "INFO"
    EMAIL_HOST: "postfix"
    EMAIL_HOST_PASSWORD: ""
    EMAIL_HOST_USER: ""
    EMAIL_PORT: 25
    EMAIL_USE_SSL: ""
    EMAIL_USE_TLS: ""
    EMAIL_TIMEOUT: ""
    ENABLE_ELECTRONIC_VOTING: "False"
    ENABLE_SAML: "False"
    INSTANCE_DOMAIN: "http://example.com:8000"
    JITSI_DOMAIN: ""
    JITSI_ROOM_PASSWORD: ""
    JITSI_ROOM_NAME: ""
    OPENSLIDES_LOG_LEVEL: "INFO"
    REDIS_CHANNLES_HOST: "redis-channels"
    REDIS_CHANNLES_PORT: 6379
    REDIS_HOST: "redis"
    REDIS_PORT: 6379
    REDIS_SLAVE_HOST: "redis-slave"
    REDIS_SLAVE_PORT: 6379
    REDIS_SLAVE_WAIT_TIMEOUT: 10000
    RESET_PASSWORD_VERBOSE_ERRORS: "False"


x-pgnode: &default-pgnode
  image: __DEFAULT_DOCKER_REGISTRY__openslides-repmgr:latest
  networks:
    - dbnet
  labels:
    org.openslides.role: "postgres"
  restart: always
x-pgnode-env: &default-pgnode-env
  REPMGR_RECONNECT_ATTEMPTS: 30
  REPMGR_RECONNECT_INTERVAL: 10
  REPMGR_WAL_ARCHIVE: "on"

services:


  server:
    image: __DEFAULT_DOCKER_REGISTRY__openslides-server:latest
    networks:
      - front
      - back
    restart: always
    # Below is the default command.  You can uncomment it to override the
    # number of workers, for example:
    #   -k uvicorn.workers.UvicornWorker openslides.asgi:application"
    #
    # command: "daphne -b 0.0.0.0 -p 8000 openslides.asgi:application"
    depends_on:
      - server-setup
    environment:
      << : *default-osserver-env
    secrets:
      - django
      
    

  server-setup:
    << : *default-osserver
    entrypoint: /usr/local/sbin/entrypoint-db-setup
    environment:
      << : *default-osserver-env
    secrets:
      - django
      - os_admin
    depends_on:
      - pgbouncer
      - redis
      - redis-slave
      - redis-channels

  client:
    image: __DEFAULT_DOCKER_REGISTRY__openslides-client:latest
    restart: always
    depends_on:
      - server
    networks:
      - front
    ports:
      - "127.0.0.1:8000:80"

  pgnode1:
    << : *default-pgnode
    environment:
      << : *default-pgnode-env
      REPMGR_NODE_ID: 1
      REPMGR_PRIMARY: # This is the primary
    volumes:
      - "dbdata1:/var/lib/postgresql"



  pgbouncer:
    environment:
      - PG_NODE_LIST=pgnode1
    image: __DEFAULT_DOCKER_REGISTRY__openslides-pgbouncer:latest
    restart: always
    networks:
      back:
        aliases:
          - db
          - postgres
      dbnet:


  postfix:
    image: __DEFAULT_DOCKER_REGISTRY__openslides-postfix:latest
    restart: always
    environment:
      MYHOSTNAME: "localhost"
      RELAYHOST: "localhost"
    networks:
      - back


  redis:
    image: redis:alpine
    restart: always
    networks:
      back:
        aliases:
          - rediscache
  redis-slave:
    image: redis:alpine
    restart: always
    command: ["redis-server", "--save", "", "--slaveof", "redis", "6379"]
    depends_on:
      - redis
    networks:
      back:
        aliases:
          - rediscache-slave
    
  redis-channels:
    image: redis:alpine
    restart: always
    networks:
      back:
  media:
    image: __DEFAULT_DOCKER_REGISTRY__openslides-media-service:latest
    environment:
      - CHECK_REQUEST_URL=server:8000/check-media/
      - CACHE_SIZE=10
      - CACHE_DATA_MIN_SIZE_KB=0
      - CACHE_DATA_MAX_SIZE_KB=10240
    restart: always
    networks:
      front:
      back:
    # Override command to run more workers per task
volumes:
  dbdata1:



networks:
  front:
  back:
  dbnet:

secrets:
  django:
    file: ./secrets/django.env
  os_admin:
    file: ./secrets/adminsecret.env
  
  

# vim: set sw=2 et: