apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-postfix
spec:
  selector:
    matchLabels:
      app: openslides-postfix
  template:
    metadata:
      labels:
        app: openslides-postfix
    spec:
      imagePullSecrets:
        - name: github-container-secret
      containers:
        - name: openslides-postfix
          image: docker.pkg.github.com/abeckdev/dlrgjugendopenslides-fork/openslides-postfix:latest
          env:
            - name: MYHOSTNAME
              value: localhost
            - name: RELAYHOST
              value: localhost
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 25
---
apiVersion: v1
kind: Service
metadata:
  name: openslides-postfix-service
spec:
  selector:
    app: openslides-postfix
  ports:
    - port: 25
      targetPort: 25
