apiVersion: v1
kind: ConfigMap
metadata:
  name: pgnode-settings
data:
  REPMGR_RECONNECT_ATTEMPTS: "30"
  REPMGR_RECONNECT_INTERVAL: "10"
  REPMGR_WAL_ARCHIVE: "on"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-pgnode
  labels:
    org.openslides.role: postgres
spec:
  selector:
    matchLabels:
      app: openslides-pgnode
  template:
    metadata:
      labels:
        app: openslides-pgnode
    spec:
      imagePullSecrets:
        - name: github-container-secret
      hostAliases:
        - ip: "127.0.0.1"
          hostnames:
            - "pgnode1"
      containers:
        - name: openslides-pgnode
          image: docker.pkg.github.com/abeckdev/dlrgjugendopenslides-fork/openslides-repmgr:latest
          command: 
          - "sleep"
          - "900000000"
          envFrom:
            - configMapRef:
                name: pgnode-settings
          env:
            - name: REPMGR_NODE_ID
              value: "1"
            - name: REPMGR_PRIMARY # This is the primary
          #volumeMounts:
          #- mountPath: /var/lib/postgresql
          # name: dbdata1
          #- mountPath: /var/lib/postgresql
          #  name: pghbaconf
          #  readOnly: False
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 22
      #volumes:
      #- name: dbdata1
      #  emptyDir: {} #Danger Mode - Persistent Volume is way better
      #- name: pghbaconf
      #  configMap:
      #    name: pgnode-hbasettings
      #    items:
      #      - key: "pg_hba.conf"
      #        path: "pg_hba.conf"

---
apiVersion: v1
kind: Service
metadata:
  name: openslides-pgnode-service
spec:
  selector:
    app: openslides-pgnode
  ports:
    - port: 22
      targetPort: 22
