apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-redis
spec:
  selector:
    matchLabels:
      app: openslides-redis
  template:
    metadata:
      labels:
        app: openslides-redis
    spec:
      containers:
        - name: openslides-redis
          image: redis:alpine
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-redis-slave
spec:
  selector:
    matchLabels:
      app: openslides-redis-slave
  template:
    metadata:
      labels:
        app: openslides-redis-slave
    spec:
      containers:
        - name: openslides-redis-slave
          image: redis:alpine
          command:
            [
              "redis-server",
              "--save",
              "",
              "--slaveof",
              "openslides-redis-master",
              "6379",
            ]
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-redis-channels
spec:
  selector:
    matchLabels:
      app: openslides-redis-channels
  template:
    metadata:
      labels:
        app: openslides-redis-channels
    spec:
      imagePullSecrets:
        - name: github-container-secret
      containers:
        - name: openslides-redis-channels
          image: docker.pkg.github.com/abeckdev/dlrgjugendopenslides-fork/openslides-media-service:latest
          env:
            - name: DB_HOST
              value: openslides-pgbouncer-service
            - name: CHECK_REQUEST_URL
              value: openslides-server-service:8000/check-media/
            - name: CACHE_SIZE
              value: "10"
            - name: CACHE_DATA_MIN_SIZE_KB
              value: "0"
            - name: CACHE_DATA_MAX_SIZE_KB
              value: "10240"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: openslides-redis-master
spec:
  selector:
    app: openslides-redis
  ports:
    - port: 6379
      targetPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  name: openslides-media-service
spec:
  selector:
    app: openslides-redis-channels
  ports:
    - port: 8000
      targetPort: 8000
