apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-pgbouncer
spec:
  selector:
    matchLabels:
      app: openslides-pgbouncer
  template:
    metadata:
      labels:
        app: openslides-pgbouncer
    spec:
      imagePullSecrets:
        - name: github-container-secret
      containers:
        - name: openslides-pgbouncer
          image: docker.pkg.github.com/abeckdev/dlrgjugendopenslides-fork/openslides-pgbouncer:latest
          env:
            - name: PG_NODE_LIST
              value: openslides-pgnode-service
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: openslides-pgbouncer-service
spec:
  selector:
    app: openslides-pgbouncer
  ports:
    - port: 5432
      targetPort: 5432
