apiVersion: apps/v1
kind: Deployment
metadata:
  name: openslides-client
spec:
  selector:
    matchLabels:
      app: openslides-client
  template:
    metadata:
      labels:
        app: openslides-client
    spec:
      imagePullSecrets:
        - name: github-container-secret
      containers:
        - name: openslides-client
          image: docker.pkg.github.com/abeckdev/dlrgjugendopenslides-fork/openslides-client:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: openslides-client-service
spec:
  selector:
    app: openslides-client
  ports:
    - port: 8000
      targetPort: 80
