apiVersion: v1
kind: Secret
metadata:
  name: openslides-secrets
type: Opaque
data:
  # Define a secret key for Django
  # https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/#secret-key
  DJANGO_SECRET_KEY: "ff"
  ## secrets/adminsecret.env is sourced by the server container to set the initial
  ## admin user password.
  OPENSLIDES_ADMIN_PASSWORD: "<securepassword>"
  ## Example user credential configuration
  # OPENSLIDES_USER_FIRSTNAME="John"
  # OPENSLIDES_USER_LASTNAME="Doe"
  # OPENSLIDES_USER_PASSWORD="<securepassword>"
  # OPENSLIDES_USER_EMAIL="john@example.com"
